export const cities = [
    { id: 'nagpur', name: 'Nagpur', members: 1284, discussions: 347, events: 12, tier: 'Tier-2', tags: ['AI/ML', 'Cloud', 'Web Dev'], active: true, state: 'Maharashtra' },
    { id: 'pune', name: 'Pune', members: 4821, discussions: 1209, events: 34, tier: 'Tier-1', tags: ['Fintech', 'DevOps', 'SaaS'], active: true, state: 'Maharashtra' },
    { id: 'indore', name: 'Indore', members: 892, discussions: 213, events: 8, tier: 'Tier-2', tags: ['Startup', 'AI', 'Mobile'], active: true, state: 'Madhya Pradesh' },
    { id: 'surat', name: 'Surat', members: 1102, discussions: 289, events: 15, tier: 'Tier-2', tags: ['Web Dev', 'E-commerce', 'Cloud'], active: true, state: 'Gujarat' },
    { id: 'hyderabad', name: 'Hyderabad', members: 6540, discussions: 2104, events: 49, tier: 'Tier-1', tags: ['Data Science', 'Cloud', 'Cybersec'], active: true, state: 'Telangana' },
    { id: 'bangalore', name: 'Bangalore', members: 11200, discussions: 4890, events: 87, tier: 'Tier-1', tags: ['AI', 'SaaS', 'DevOps', 'Startups'], active: true, state: 'Karnataka' },
    { id: 'jaipur', name: 'Jaipur', members: 743, discussions: 178, events: 7, tier: 'Tier-2', tags: ['Web Dev', 'EdTech', 'Mobile'], active: false, state: 'Rajasthan' },
    { id: 'bhopal', name: 'Bhopal', members: 512, discussions: 94, events: 4, tier: 'Tier-2', tags: ['AI', 'Cloud', 'Web Dev'], active: false, state: 'Madhya Pradesh' },
    { id: 'lucknow', name: 'Lucknow', members: 834, discussions: 196, events: 9, tier: 'Tier-2', tags: ['GovTech', 'Web Dev', 'Fintech'], active: false, state: 'Uttar Pradesh' },
    { id: 'kochi', name: 'Kochi', members: 1456, discussions: 389, events: 18, tier: 'Tier-2', tags: ['IoT', 'Cloud', 'Blockchain'], active: true, state: 'Kerala' },
    { id: 'ahmedabad', name: 'Ahmedabad', members: 2108, discussions: 567, events: 21, tier: 'Tier-1', tags: ['SaaS', 'HealthTech', 'AI'], active: true, state: 'Gujarat' },
    { id: 'chandigarh', name: 'Chandigarh', members: 678, discussions: 142, events: 6, tier: 'Tier-2', tags: ['Web Dev', 'AgriTech', 'DevOps'], active: false, state: 'Punjab' },
];

export const discussions = [
    {
        id: 1,
        title: 'Building a Retrieval-Augmented Generation (RAG) pipeline for internal knowledge bases',
        author: { name: 'Rahul Sharma', role: 'ML Engineer', avatar: 'RS', city: 'Nagpur' },
        category: 'AI/ML',
        tags: ['RAG', 'LLM', 'Python', 'LangChain'],
        upvotes: 142,
        replies: 38,
        views: 1240,
        timeAgo: '3 hours ago',
        preview: 'Has anyone built a production-grade RAG pipeline? Looking for advice on chunking strategies and embedding models that work best for technical documentation.',
        pinned: true,
    },
    {
        id: 2,
        title: 'Architecture patterns for multi-tenant SaaS applications on AWS',
        author: { name: 'Priya Nair', role: 'Cloud Architect', avatar: 'PN', city: 'Pune' },
        category: 'Cloud',
        tags: ['AWS', 'Architecture', 'SaaS', 'Multi-tenant'],
        upvotes: 98,
        replies: 24,
        views: 876,
        timeAgo: '6 hours ago',
        preview: 'What are the best approaches for handling tenant isolation at the database level? Shared schema vs separate schemas vs separate databases?',
        pinned: false,
    },
    {
        id: 3,
        title: 'How are you handling React Server Components in large codebases?',
        author: { name: 'Arjun Mehta', role: 'Frontend Engineer', avatar: 'AM', city: 'Nagpur' },
        category: 'Web Dev',
        tags: ['React', 'Next.js', 'RSC', 'TypeScript'],
        upvotes: 76,
        replies: 19,
        views: 623,
        timeAgo: '1 day ago',
        preview: 'Migrating a large Next.js project to use RSC. What patterns are working for you to avoid prop drilling while still leveraging server components?',
        pinned: false,
    },
    {
        id: 4,
        title: 'Kubernetes costs getting out of control — optimization tips?',
        author: { name: 'Deepak Singh', role: 'DevOps Engineer', avatar: 'DS', city: 'Hyderabad' },
        category: 'DevOps',
        tags: ['Kubernetes', 'K8s', 'Cost Optimization', 'GKE'],
        upvotes: 112,
        replies: 31,
        views: 945,
        timeAgo: '2 days ago',
        preview: 'K8s bills have tripled after scaling up. Which tools (Kubecost, Goldilocks, VPA) have made a tangible difference for your team?',
        pinned: false,
    },
    {
        id: 5,
        title: 'LLM fine-tuning vs prompt engineering — what is actually worth the effort?',
        author: { name: 'Neha Kulkarni', role: 'AI Engineer', avatar: 'NK', city: 'Nagpur' },
        category: 'AI/ML',
        tags: ['LLM', 'Fine-tuning', 'Prompt Engineering', 'GPT'],
        upvotes: 184,
        replies: 52,
        views: 1890,
        timeAgo: '3 days ago',
        preview: 'After spending 2 weeks on fine-tuning Mistral vs better prompt engineering, here are my results and thoughts on which approach gave better ROI.',
        pinned: false,
    },
    {
        id: 6,
        title: 'Postgresql vs MongoDB in 2025 — for a real-time collaboration app',
        author: { name: 'Vikram Patil', role: 'Backend Engineer', avatar: 'VP', city: 'Nagpur' },
        category: 'System Design',
        tags: ['PostgreSQL', 'MongoDB', 'Database', 'System Design'],
        upvotes: 67,
        replies: 43,
        views: 712,
        timeAgo: '4 days ago',
        preview: 'Building a Figma-like tool. Considering CRDTs + PostgreSQL but MongoDB\'s document model seems more natural for the nested component tree. Thoughts?',
        pinned: false,
    },
];

export const projects = [
    {
        id: 1,
        title: 'AI-Powered Traffic Management System for Smart Cities',
        description: 'Building a computer vision based traffic optimization system using YOLOv8 + reinforcement learning for adaptive signal control. Pilot project for Nagpur Smart City initiative.',
        author: { name: 'Rahul Sharma', role: 'ML Engineer', avatar: 'RS' },
        city: 'Nagpur',
        type: 'Research',
        techStack: ['Python', 'PyTorch', 'YOLOv8', 'FastAPI', 'React'],
        lookingFor: ['ML Engineer', 'Computer Vision', 'Backend Dev'],
        teamSize: '3/6',
        status: 'Active',
        postedAgo: '2 days ago',
    },
    {
        id: 2,
        title: 'Open-Source DevOps Cost Analyzer CLI Tool',
        description: 'CLI + web dashboard that aggregates cloud spending across AWS, GCP, and Azure and surfaces actionable cost optimization recommendations using ML models.',
        author: { name: 'Deepak Singh', role: 'DevOps Engineer', avatar: 'DS' },
        city: 'Hyderabad',
        type: 'Open Source',
        techStack: ['Go', 'Rust', 'React', 'PostgreSQL', 'Terraform'],
        lookingFor: ['Go Developer', 'Frontend Dev', 'Cloud Architect'],
        teamSize: '2/5',
        status: 'Active',
        postedAgo: '5 days ago',
    },
    {
        id: 3,
        title: 'AgriTech Platform for Direct Farmer-Consumer Connect',
        description: 'Marketplace and supply chain platform connecting farmers directly with urban consumers, eliminating middlemen. Includes quality grading using AI and logistics routing.',
        author: { name: 'Priya Nair', role: 'Startup Founder', avatar: 'PN' },
        city: 'Pune',
        type: 'Startup',
        techStack: ['React Native', 'Node.js', 'MongoDB', 'AWS'],
        lookingFor: ['Mobile Dev', 'Backend Dev', 'UI/UX Designer'],
        teamSize: '2/4',
        status: 'Ideation',
        postedAgo: '1 week ago',
    },
    {
        id: 4,
        title: 'Distributed Feature Store for ML Teams',
        description: 'Open-source feature store that integrates with existing data pipelines (Spark, dbt, Airflow) and serves features at low latency for both training and inference.',
        author: { name: 'Neha Kulkarni', role: 'Data Engineer', avatar: 'NK' },
        city: 'Nagpur',
        type: 'Open Source',
        techStack: ['Python', 'Apache Arrow', 'Redis', 'Kafka', 'dbt'],
        lookingFor: ['Data Engineer', 'Backend Dev', 'ML Platform Eng'],
        teamSize: '1/4',
        status: 'Recruiting',
        postedAgo: '2 weeks ago',
    },
];

export const events = [
    {
        id: 1,
        title: 'DevCircle Nagpur — AI/ML Hack Night',
        description: 'An evening of hacking, collaboration, and learning. Build AI prototypes in 4 hours with fellow ML engineers. Prizes for best demos!',
        city: 'Nagpur',
        type: 'Hack Night',
        date: 'March 15, 2026',
        time: '6:00 PM – 11:00 PM',
        venue: 'T-Hub Nagpur, Sitabuldi',
        rsvp: 48,
        capacity: 80,
        tags: ['AI', 'ML', 'Hackathon'],
        organizer: 'DevCircle Nagpur Core Team',
        fee: 'Free',
        upcoming: true,
    },
    {
        id: 2,
        title: 'System Design Masterclass — Distributed Systems at Scale',
        description: 'Deep-dive into designing distributed systems. Covers CAP theorem, consensus algorithms, and real-world case studies from engineers who\'ve scaled to millions.',
        city: 'Nagpur',
        type: 'Workshop',
        date: 'March 22, 2026',
        time: '10:00 AM – 2:00 PM',
        venue: 'IIM Nagpur, Mihan',
        rsvp: 67,
        capacity: 100,
        tags: ['System Design', 'Architecture', 'Distributed'],
        organizer: 'Arjun Mehta',
        fee: '₹199',
        upcoming: true,
    },
    {
        id: 3,
        title: 'Cloud Cost Optimization — DevOps Fireside Chat',
        description: 'Three senior DevOps engineers share real-world strategies for cutting cloud costs without sacrificing reliability. Q&A session included.',
        city: 'Pune',
        type: 'Talk',
        date: 'March 29, 2026',
        time: '7:00 PM – 9:00 PM',
        venue: 'WeWork Baner, Pune',
        rsvp: 112,
        capacity: 150,
        tags: ['DevOps', 'Cloud', 'AWS', 'Cost'],
        organizer: 'DevCircle Pune',
        fee: 'Free',
        upcoming: true,
    },
    {
        id: 4,
        title: 'Open Source Contribution Sprint — April Edition',
        description: 'Contribute to meaningful open-source projects with experienced maintainers guiding first-time contributors. All skill levels welcome.',
        city: 'Nagpur',
        type: 'Contribution Sprint',
        date: 'April 5, 2026',
        time: '9:00 AM – 5:00 PM',
        venue: 'VNIT Innovation Hub',
        rsvp: 34,
        capacity: 60,
        tags: ['Open Source', 'Community', 'Mentorship'],
        organizer: 'DevCircle Nagpur',
        fee: 'Free',
        upcoming: true,
    },
    {
        id: 5,
        title: 'Startup Engineering Night — Lessons from 0 to 10K users',
        description: 'Founders share the technical decisions and trade-offs they made while scaling from zero to their first 10,000 users. Panel discussion format.',
        city: 'Hyderabad',
        type: 'Panel',
        date: 'April 12, 2026',
        time: '6:30 PM – 9:00 PM',
        venue: 'T-Hub Hyderabad',
        rsvp: 189,
        capacity: 200,
        tags: ['Startup', 'Engineering', 'Scaling'],
        organizer: 'DevCircle Hyderabad',
        fee: 'Free',
        upcoming: true,
    },
];

export const members = [
    { name: 'Rahul Sharma', role: 'ML Engineer', company: 'Infosys', experience: '4 yrs', skills: ['Python', 'PyTorch', 'AWS', 'MLflow'], avatar: 'RS', city: 'Nagpur' },
    { name: 'Neha Kulkarni', role: 'AI Researcher', company: 'TCS Research', experience: '6 yrs', skills: ['NLP', 'LLM', 'Python', 'HuggingFace'], avatar: 'NK', city: 'Nagpur' },
    { name: 'Arjun Mehta', role: 'Frontend Engineer', company: 'Nagpur Startup Co.', experience: '3 yrs', skills: ['React', 'TypeScript', 'Next.js', 'Tailwind'], avatar: 'AM', city: 'Nagpur' },
    { name: 'Vikram Patil', role: 'Backend Engineer', company: 'Freelance', experience: '5 yrs', skills: ['Go', 'PostgreSQL', 'Kafka', 'Docker'], avatar: 'VP', city: 'Nagpur' },
    { name: 'Shruti Wagh', role: 'DevOps Engineer', company: 'Hexaware', experience: '7 yrs', skills: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD'], avatar: 'SW', city: 'Nagpur' },
    { name: 'Kiran Desai', role: 'Data Scientist', company: 'CRISIL', experience: '5 yrs', skills: ['Python', 'Spark', 'SQL', 'Tableau'], avatar: 'KD', city: 'Nagpur' },
];

export const categories = [
    { id: 'ai-ml', label: 'AI / ML', count: 124, icon: '🤖' },
    { id: 'cloud', label: 'Cloud Computing', count: 89, icon: '☁️' },
    { id: 'web-dev', label: 'Web Development', count: 156, icon: '🌐' },
    { id: 'devops', label: 'DevOps', count: 67, icon: '⚙️' },
    { id: 'cybersec', label: 'Cybersecurity', count: 43, icon: '🔒' },
    { id: 'system-design', label: 'System Design', count: 98, icon: '🏗️' },
    { id: 'startup', label: 'Startup Engineering', count: 72, icon: '🚀' },
    { id: 'data', label: 'Data Engineering', count: 55, icon: '📊' },
];
