// Mock data for unauthenticated or empty states

export const MockUsers = [
    {
        id: "mock-user-1",
        name: "Alex Dev",
        email: "alex@example.com",
        image: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
        role: "USER",
        cityId: "nagpur",
        bio: "Full-stack developer passionate about open source and community building.",
        company: "Tech Corp",
        jobTitle: "Senior Engineer",
        experienceLevel: "Senior",
        skills: "React, Node.js, TypeScript, PostgreSQL",
        interests: "Web3, AI, Open Source",
        github: "https://github.com/alexdev",
        portfolioUrl: "https://alexdev.com",
        openToMentoring: true,
        openToCollaborate: true,
        reputation: 1500,
        followersCount: 120,
        followingCount: 45,
        onboarded: true,
        createdAt: new Date("2024-01-15"),
        City: { name: "Nagpur" }
    },
    {
        id: "mock-user-2",
        name: "Sarah Designer",
        email: "sarah@example.com",
        image: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
        role: "USER",
        cityId: "nagpur",
        bio: "UI/UX Designer creating intuitive and beautiful digital experiences.",
        company: "Design Studio",
        jobTitle: "Lead Designer",
        experienceLevel: "Mid-Level",
        skills: "Figma, UI/UX, Design Systems, CSS",
        interests: "Accessibility, CSS Architecture",
        github: null,
        portfolioUrl: "https://sarahdesigns.com",
        openToMentoring: false,
        openToCollaborate: true,
        reputation: 850,
        followersCount: 89,
        followingCount: 112,
        onboarded: true,
        createdAt: new Date("2024-02-20"),
        City: { name: "Nagpur" }
    },
    {
        id: "mock-user-3",
        name: "David Data",
        email: "david@example.com",
        image: "https://i.pravatar.cc/150?u=a04258114e29026702d",
        role: "USER",
        cityId: "pune",
        bio: "Data Scientist turning coffee into machine learning models.",
        company: "AI Innovations",
        jobTitle: "Data Scientist",
        experienceLevel: "Senior",
        skills: "Python, PyTorch, SQL, Pandas",
        interests: "Machine Learning, NLP, Big Data",
        github: "https://github.com/daviddata",
        portfolioUrl: null,
        openToMentoring: true,
        openToCollaborate: false,
        reputation: 2100,
        followersCount: 340,
        followingCount: 20,
        onboarded: true,
        createdAt: new Date("2023-11-05"),
        City: { name: "Pune" }
    },
    {
        id: "mock-user-4",
        name: "Priya Mobile",
        email: "priya@example.com",
        image: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
        role: "USER",
        cityId: "nagpur",
        bio: "iOS Developer building delightful mobile experiences.",
        company: "App Works",
        jobTitle: "Mobile Developer",
        experienceLevel: "Junior",
        skills: "Swift, iOS, React Native",
        interests: "Mobile Development, AR/VR",
        github: "https://github.com/priyamobile",
        portfolioUrl: null,
        openToMentoring: false,
        openToCollaborate: true,
        reputation: 420,
        followersCount: 45,
        followingCount: 67,
        onboarded: true,
        createdAt: new Date("2024-05-10"),
        City: { name: "Nagpur" }
    }
];

export const MockProjects = [
    {
        id: "mock-proj-1",
        title: "DevCircle Platform",
        description: "A community-driven platform connecting local developers. We are building the next generation of hyper-local tech communities.",
        content: "Detailed content about the DevCircle platform architecture...",
        status: "Active",
        type: "Open Source",
        techStack: "Next.js, Prisma, PostgreSQL, UI/UX",
        lookingFor: "Frontend Developers, UI Designers",
        repositoryUrl: "https://github.com/devcircle",
        applicationUrl: null,
        websiteUrl: "https://devcircle.com",
        teamSize: 5,
        targetAudience: "Developers",
        businessModel: "Open Source",
        createdAt: new Date(),
        authorId: MockUsers[0].id,
        cityId: "nagpur",
        author: MockUsers[0],
        city: { name: "Nagpur" },
        _count: { projectMembers: 5 }
    },
    {
        id: "mock-proj-2",
        title: "AI Code Assistant",
        description: "Building a fine-tuned local LLM specifically optimized for context-aware codebase refactoring.",
        content: "Detailed content about the AI project...",
        status: "Recruiting",
        type: "Startup",
        techStack: "Python, PyTorch, React, FastAPI",
        lookingFor: "Machine Learning Engineers",
        repositoryUrl: null,
        applicationUrl: null,
        websiteUrl: null,
        teamSize: 2,
        targetAudience: "Developers",
        businessModel: "SaaS",
        createdAt: new Date(Date.now() - 86400000 * 2), // 2 days ago
        authorId: MockUsers[2].id,
        cityId: "pune",
        author: MockUsers[2],
        city: { name: "Pune" },
        _count: { projectMembers: 2 }
    },
    {
        id: "mock-proj-3",
        title: "Accessibility Audit Tool",
        description: "A browser extension that automatically audits websites against WCAG 2.1 guidelines.",
        content: "Detailed content...",
        status: "Ideation",
        type: "Open Source",
        techStack: "TypeScript, Browser Extension API",
        lookingFor: "Accessibility Experts, Testers",
        repositoryUrl: "https://github.com/a11y-tool",
        applicationUrl: null,
        websiteUrl: null,
        teamSize: 1,
        targetAudience: "Web Developers",
        businessModel: "Free Tool",
        createdAt: new Date(Date.now() - 86400000 * 5), // 5 days ago
        authorId: MockUsers[1].id,
        cityId: "nagpur",
        author: MockUsers[1],
        city: { name: "Nagpur" },
        _count: { projectMembers: 1 }
    }
];

export const MockEvents = [
    {
        id: "mock-event-1",
        title: "Next.js Architecture Deep Dive",
        description: "Join us for an advanced session on building scalable applications with Next.js App Router and Server Actions.",
        content: "Full description...",
        date: new Date(Date.now() + 86400000 * 5), // 5 days from now
        time: "18:00",
        venue: "Tech Hub, IT Park",
        type: "Meetup",
        capacity: 50,
        fee: "Free",
        registrationUrl: null,
        createdAt: new Date(),
        organizerId: MockUsers[0].id,
        cityId: "nagpur",
        organizer: MockUsers[0],
        city: { name: "Nagpur" },
        _count: { rsvps: 24 }
    },
    {
        id: "mock-event-2",
        title: "Central India Hackathon 2026",
        description: "A 48-hour hackathon focused on building AI solutions for local businesses.",
        content: "Full description...",
        date: new Date(Date.now() + 86400000 * 14), // 14 days from now
        time: "09:00",
        venue: "Symbiosis Auditorium",
        type: "Hackathon",
        capacity: 200,
        fee: "RS 500",
        registrationUrl: "https://hackathon.example.com",
        createdAt: new Date(Date.now() - 86400000 * 10),
        organizerId: MockUsers[0].id,
        cityId: "nagpur",
        organizer: MockUsers[0],
        city: { name: "Nagpur" },
        _count: { rsvps: 156 }
    },
    {
        id: "mock-event-3",
        title: "Women in Tech: Design Systems",
        description: "A workshop on building and maintaining scalable design systems in Figma and React.",
        content: "Full description...",
        date: new Date(Date.now() + 86400000 * 8), // 8 days from now
        time: "17:30",
        venue: "Design Co-working",
        type: "Workshop",
        capacity: 30,
        fee: "Free",
        registrationUrl: null,
        createdAt: new Date(Date.now() - 86400000 * 3),
        organizerId: MockUsers[1].id,
        cityId: "nagpur",
        organizer: MockUsers[1],
        city: { name: "Nagpur" },
        _count: { rsvps: 28 }
    }
];

export const MockDiscussions = [
    {
        id: "mock-disc-1",
        title: "What's everyone's preferred state management in React right now?",
        content: "Are we still doing Redux, or has everyone moved to Zustand/Jotai?",
        category: "Tech Stack",
        tags: "React, Frontend, State Management",
        createdAt: new Date(),
        authorId: MockUsers[0].id,
        cityId: "nagpur",
        author: MockUsers[0],
        _count: { comments: 12, upvotes: 24 }
    },
    {
        id: "mock-disc-2",
        title: "Looking for recommendations for local co-working spaces",
        content: "Working from home is getting lonely. Any good co-working spaces with reliable internet?",
        category: "Career & Work",
        tags: "Remote Work, Co-working, Local",
        createdAt: new Date(Date.now() - 86400000 * 1),
        authorId: MockUsers[1].id,
        cityId: "nagpur",
        author: MockUsers[1],
        _count: { comments: 8, upvotes: 15 }
    },
    {
        id: "mock-disc-3",
        title: "Who is attending the upcoming AI meetup next week?",
        content: "Would love to catch up with some folks from the community before the talks start.",
        category: "Events",
        tags: "Meetup, Networking",
        createdAt: new Date(Date.now() - 86400000 * 2),
        authorId: MockUsers[3].id,
        cityId: "nagpur",
        author: MockUsers[3],
        _count: { comments: 5, upvotes: 9 }
    }
];
